---
abstract: 'Desktop nagios-inspired events watcher/notifier'
author:
  - 'Ivan Baidakou <dmol@gmx.com>'
build_requires:
  AnyEvent::HTTPD: 0.93
  Test::More: 0.98
  Test::TCP: 1.26
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PerlWatcher-Engine
requires:
  AnyEvent: 7.04
  AnyEvent::HTTP: 2.15
  Devel::Comments: v1.1.4
  File::ReadBackwards: 1.05
  File::ShareDir::ProjectDistDir: v0.4.4
  HTTP::Date: 6.02
  Linux::Inotify2: 1.22
  Moo: 1.003000
  Storable: 2.45
  XML::Simple: 2.18
  XML::XPath: 1.13
  aliased: 0.31
version: 0.12
