---
abstract: 'Desktop nagios-inspired events watcher/notifier'
author:
  - 'Ivan Baidakou <dmol@gmx.com>'
build_requires:
  AnyEvent::HTTPD: 0.93
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
  Test::TCP: 1.26
configure_requires:
  ExtUtils::MakeMaker: 6.72
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300036, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PerlWatcher-Engine
requires:
  AnyEvent: 7.04
  AnyEvent::HTTP: 2.15
  Class::Load: 0.20
  Data::Dump: 1.22
  File::ReadBackwards: 1.05
  File::ShareDir::ProjectDistDir: v0.4.4
  HTTP::Date: 6.02
  IPC::Run3: 0.045
  Linux::Inotify2: 1.22
  List::MoreUtils: 0.33
  Moo: 1.003000
  Net::Ping::External: 0.13
  Path::Class: 0.31
  Smart::Comments: 1.000004
  Storable: 2.45
  URI: 1.60
  XML::Simple: 2.18
  XML::XPath: 1.13
  aliased: 0.31
  perl: 5.012
resources:
  repository: https://github.com/basiliscos/perl-watcher.git
version: 0.17
