#!/usr/bin/env perl

use 5.12.0;
use strict;
use warnings;

use Carp;
use Devel::Comments;
use FindBin;

BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use App::PerlWatcher::Application;
use App::PerlWatcher::Engine;
use App::PerlWatcher::Watcher::Ping;
use App::PerlWatcher::Watcher::FileTail;

my $frequency = 15;
my $timeout   = 1;

my $config_file = $ARGV[0];

open(my $config_fh, "<", $config_file) 
    or croak("Can't open config file $config_file");

my $content_config = do { local $/ = <$config_fh> };
my $config = eval $content_config ;

my $engine = App::PerlWatcher::Engine->new($config);

my $app = App::PerlWatcher::Application->new($engine);
$app->show;
$app->update( [] );

$engine->frontend($app);

$engine->start;

1;
