#!/usr/bin/env perl

use 5.12.0;
use strict;
use warnings;

use Carp;
use Devel::Comments;
use FindBin;

BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use App::PerlWatcher::Bootstrap qw/startup frontend/;
use App::PerlWatcher::Engine;

my $config = startup;
my $backend = 'Gtk2';
my $engine = App::PerlWatcher::Engine->new($config, $backend);
my $app = frontend($backend, $engine);
$engine->frontend( $app );

$app->show;
$engine->start;

1;
