#!/usr/bin/env perl

use 5.12.0;
use strict;
use warnings;

use FindBin;

BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use App::PerlWatcher::Application;
use App::PerlWatcher::Engine;
use App::PerlWatcher::Watcher::Ping;
use App::PerlWatcher::Watcher::FileTail;

my $frequency = 15;
my $timeout   = 1;

my $config = {
    frontend => {
        gtk => {
            window_size => [ 500, 300 ],
        },
    },
};

my @watchers = (
    App::PerlWatcher::Watcher::Ping->new(
        'basiliscos', 443, $frequency, $timeout
    ),
    App::PerlWatcher::Watcher::Ping->new(
        'media.iptel.by', 80, $frequency, $timeout
    ),
    App::PerlWatcher::Watcher::Ping->new(
        'iptel.by', 80, $frequency, $timeout
    ),
    App::PerlWatcher::Watcher::Ping->new(
        'google.com', 80, $frequency, $timeout
    ),
    App::PerlWatcher::Watcher::Ping->new( 'helios', 53, $frequency, $timeout ),
    App::PerlWatcher::Watcher::FileTail->new( '/var/log/messages', 10 ),
);

my $engine = App::PerlWatcher::Engine->new( \@watchers, $config );

my $app = App::PerlWatcher::Application->new($engine);
$app->show;
$app->update( [] );

$engine->frontend($app);

$engine->start;

1;
